#!/bin/bash

#####################################
#
#       Created by: zacharyd3
#
#####################################


#Start Debugging (set as 1 to enable basic info, 2 enables all steps to show and 3 shows all steps and comparison info)
debug=1
#Enable testing mode to simulate the move without actually moving any files (0 = moves files, 1 = Test)
testing=0

#If testing is enabled, automatically switch to debug mode 2
if [[ $testing -eq 1 && $debug -le 2 ]]; then
	debug=2
	echo "<font color='blue'><b>Testing is enabled, enabling advanced debugging.</b></font>"
fi

#Start counting the renaming passes made
passNumber=1

#Set radarr recycle bin location
binMovie=/mnt/user/Downloads/.Recycle.Bin/Movies/
binTV=/mnt/user/Downloads/.Recycle.Bin/TV/

#Set the library locations
movieFolderRoot=/mnt/user/Videos/Movies/
tvFolderRoot=/mnt/user/Videos/TV/

#Ensures the recycle bin is setup properly
echo "<hr>"
echo "<font color='blue'><b>Recycle Bin scan started!</b></font>"
echo ""
echo "<hr>"

#Checks if the movies recycle bin exists
if [[ ! -d "${binMovie}" ]]; then
	echo "<font color='orange'><b>Movie bin not found!</b></font>"
#Creates missing directory
	mkdir "${binMovie}"
	echo "<font color='green'><b>Directory created.</b></font>"
	else
	echo "<font color='green'><b>Movie bin already exists.</b></font>"
fi

#Checks if the tv show recycle bin exists
if [[ ! -d "${binTV}" ]]; then
	echo "<font color='orange'><b>TV Show bin not found!</b></font>"
#Creates missing directory
	mkdir "${binTV}"
	echo "<font color='green'><b>Directory created.</b></font>"
else
	echo "<font color='green'><b>TV Show bin already exists.</b></font>"
fi
echo ""

#####################################
#
#         Low-res Movie Sorter
#
#####################################

inUse=0
cCheck=0

echo "<hr>"
echo "<font color='blue'><b>Copying Low-res movies back.</b></font>"
echo ""
echo "<hr>"

#Run the next commands on each file in the recycle bin
for file in $binMovie*
do
#Start checking Movies.
	if [ -d "${file}" ]; then
		directory=$file/
		for movieFile in "${directory}"*
		do
			if [ -f "${movieFile}" ]; then
#Parse movie name from filenames found ( Change the number after "F" to how many directories there are before the recycle bin and add 2. )
				parseNameOld0=$(echo "$movieFile" | cut -d'/' -f8) #<<Change this number
				parseNameOld1=$(echo "$parseNameOld0" | cut -d'(' -f1)
				parseNameOld2=${parseNameOld1::-2}
				parseNameOld2=$(echo $parseNameOld2 | xargs) #xargs removes leading and trailing whitespace.
				if [ $debug -ge "1" ]; then
					echo "<font color='green'><b>Original Movie name: </b></font>"$parseNameOld2
				fi
#Check if the recycled file is 1080p.
				if [[ $movieFile != *"1080p"* ]]; then
					if [ $debug -ge "1" ]; then
						echo "<font color='orange'><b>The file is not 1080p, skipping.</b></font>"
						echo ""
						break
					else
						let cCheck=1
					fi
				fi
#Check if the file is in use.
				if lsof "$movieFile" > /dev/null; then
					echo "<font color='orange'><b>File is in use, skipping.</b></font>"
					echo ""
					inUse=1
					break
				else
					inUse=0
				fi
#Parse file extension
				parseExt=$(echo "$movieFile" | cut -d'.' -f5)
#Turn the parsed movie name into a folder
				movieFolder0=$movieFolderRoot$parseNameOld2
				movieFolder1="${movieFolder0}/"
				if [ $debug -ge "2" ]; then
					echo "<font color='green'><b>Searching for 4K Movie folder: </b></font>"$movieFolder1
				fi
#Test if the movie folder exists
				if [ -d "${movieFolder1}" ]; then
					cd "${movieFolder1}"
#Search the folder for 4K movies
					foundNew=$(find . -maxdepth 1 -name "*2160p*" -size +1536M)
					if [[ "$foundNew" != "" ]]; then
						if [ $debug -ge "1" ]; then
							echo "<font color='green'><b>Found matching 4K Movie: </b></font>"$foundNew
						fi
					fi
					if [[ "$foundNew" = "" ]]; then
						echo "<font color='orange'><b>No matching 4K file found, skipping.</b></font>"
					fi
#Parse movie name only if 4K filename found
					if [[ "$foundNew" == *"2160p"* ]]; then
						parseNameNew0=$(echo "$foundNew" | cut -d'[' -f1)
						parseNameNew1=$(echo "$parseNameNew0" | cut -d'/' -f2)
						parseNameNew2=${parseNameNew1}
						parseNameNew2=$(echo $parseNameNew2 | xargs) #xargs removes leading and trailing whitespace
						if [ $debug -ge "2" ]; then
							echo "<font color='red'><b>Name Comparison:</b></font> |" $parseNameOld2 "|" $parseNameNew2 "|"
						fi
							if [ "${parseNameOld2}" == "${parseNameNew2}" ]; then
								if [ "${parseExt}" != "nfo" ]; then
									if [ $debug -ge "2" ] && [ $inUse -eq "0" ]; then
										echo "<font color='red'><b>Files Checked: </b></font>"$passNumber
									fi
									let passNumber++
									if [ $testing -eq "0" ]; then
										mv "${movieFile}" "${movieFolder1}"
									fi
									/usr/local/emhttp/webGui/scripts/notify -e "Radarr Copy" -s "Copy Notifcation" -d "$parseNameNew2 $parseExt has been copied back." -i "normal"
									echo "<font color='green'><b>"$parseNameNew2" "$parseExt" moved.</b></font>"
									echo ""
								fi
							fi
						fi
					fi
					if [ $debug -ge "1" ]; then
						echo ""
					fi
				fi
		done
	fi
done

if [[ passNumber -eq "1" ]]; then
echo "No files to process"
echo ""
echo ""
fi

#####################################
#
#         4K Movie Sorter
#
#####################################

passNumber=1
inUse=0
cCheck=0

echo "<hr>"
echo "<font color='blue'><b>Copying 4K Movies back.</b></font>"
echo ""
echo "<hr>"

#Run the next commands on each file in the recycle bin
for file in $binMovie*
do
#Start checking Movies.
	if [ -d "${file}" ]; then
		directory=$file/
		for movieFile in "${directory}"*
		do
			if [ -f "${movieFile}" ]; then
#Parse movie name from filenames found ( Change the number after "F" to how many directories there are before the recycle bin and add 2. )
				parseNameOld0=$(echo "$movieFile" | cut -d'/' -f8) #<<Change this number
				parseNameOld1=$(echo "$parseNameOld0" | cut -d'(' -f1)
				parseNameOld2=${parseNameOld1::-2}
				parseNameOld2=$(echo $parseNameOld2 | xargs) #xargs removes leading and trailing whitespace.
				if [ $debug -ge "1" ]; then
					echo "<font color='green'><b>Original Movie name: </b></font>"$parseNameOld2
				fi
#Check if the recycled file is 4K.
				if [[ $movieFile != *"2160p"* ]]; then
					if [ $debug -ge "1" ]; then
						echo "<font color='orange'><b>The file is not 4K, skipping.</b></font>"
						echo ""
						break
					else
						let cCheck=1
					fi
				fi
#Check if the file is in use.
				if lsof "$movieFile" > /dev/null; then
					echo "<font color='orange'><b>File is in use, skipping.</b></font>"
					echo ""
					inUse=1
					break
				else
					inUse=0
				fi
#Parse file extension
				parseExt=$(echo "$movieFile" | cut -d'.' -f5)
#Turn the parsed movie name into a folder
				movieFolder0=$movieFolderRoot$parseNameOld2
				movieFolder1="${movieFolder0}/"
				if [ $debug -ge "1" ]; then
					echo "<font color='green'><b>Searching for Low-res Movie folder: </b></font>"$movieFolder1
				fi
#Test if the movie folder exists
				if [ -d "${movieFolder1}" ]; then
					cd "${movieFolder1}"
#Search the folder for Low-res movies
					foundNew=$(find . -maxdepth 1 -name "*1080p*" -size +1536M)
					if [[ "$foundNew" != "" ]]; then
						if [ $debug -ge "1" ]; then
							echo "<font color='green'><b>Found matching Low-res Movie: </b></font>"$foundNew
						fi
					fi
					if [[ "$foundNew" = "" ]]; then
						echo "<font color='orange'><b>No matching Low-res file found, skipping.</b></font>"
					fi
#Parse movie name only if Low-res filename found
				if [[ "$foundNew" == *"1080p"* ]]; then
					parseNameNew0=$(echo "$foundNew" | cut -d'[' -f1)
					parseNameNew1=$(echo "$parseNameNew0" | cut -d'/' -f2)
					parseNameNew2=${parseNameNew1}
					parseNameNew2=$(echo $parseNameNew2 | xargs) #xargs removes leading and trailing whitespace
					if [ $debug -ge "2" ]; then
						echo "<font color='red'><b>Name Comparison:</b></font> |" $parseNameOld2 "|" $parseNameNew2 "|"
					fi
						if [ "${parseNameOld2}" == "${parseNameNew2}" ]; then
							if [ "${parseExt}" != "nfo" ]; then
								if [ $debug -ge "2" ] && [ $inUse -eq "0" ]; then
									echo "<font color='red'><b>Files Checked: </b></font>"$passNumber
								fi
								let passNumber++
								if [ $testing -eq "0" ]; then
									mv "${movieFile}" "${movieFolder1}"
								fi
								/usr/local/emhttp/webGui/scripts/notify -e "Radarr Copy" -s "Copy Notifcation" -d "$parseNameNew2 $parseExt has been copied back." -i "normal"
								echo "<font color='green'><b>"$parseNameNew2" "$parseExt" moved.</b></font>"
								echo ""
							fi
						fi
					fi
				fi
				if [ $debug -ge "1" ]; then
					echo ""
				fi
			fi
		done
	fi
done

if [[ passNumber -eq "1" ]]; then
echo "No files to process"
echo ""
echo ""
fi

#####################################
#
#          TV Show Sorter
#
#####################################

passNumber=1 #Counts how many files have been checked
inUse=0 #Saves if the file is in use and cancels
rCheck=0 #Set to 0 if it's ok to continue, 1 if it should end. (stands for Resolution Check)
vCheck=0 #Set to 0 if it's ok to continue, 1 if it skip the current file. (stands for Video Check)

echo "<hr>"
echo "<font color='blue'><b>Copying Low-res TV Show's back.</b></font>"
echo ""
echo "<hr>"

for file in $binTV*
do
#Start checking TV shows.
	if [ "$(ls -A "$file")" ]; then
		directory=$file/
		for tvSeason in "${directory}"*/*
		do
			if [ -f "${tvSeason}" ]; then
				if [ $debug -ge "2" ]; then
					echo "<font color='green'><b>Full name: </b></font>"$tvSeason
				fi
#Parse the show name, episode and season
				parseNameOld0=$(echo "$tvSeason" | cut -d'/' -f9)
				parseNameOld0=$(echo "$parseNameOld0" | cut -d'[' -f1)
				tvShowName=$(echo "$tvSeason" | cut -d'/' -f7)
				tvShowSeason=$(echo "$tvSeason" | cut -d'/' -f8)
				tvShowEpisode0=$(echo "$tvSeason" | cut -d'/' -f9)
				tvShowEpisode1=$(echo "$tvShowEpisode0" | cut -d'-' -f1)
				if [ $debug -ge "1" ]; then
					echo "<font color='green'><b>Show name: </b></font>"$tvShowName
					echo "<font color='green'><b>Show episode: </b></font>"$tvShowEpisode1
				fi
#Check if the file is a video
				if [[ $tvSeason == *"mkv" ]]; then
					let vCheck=0 #Resets the Video Check for a new file
					let rCheck=0 #Resets the Continue Check for a new file
				else 
					echo "<font color='orange'><b>File isn't a video, skipping</b></font>"
					echo ""
					let vCheck=1					
				fi
#Ensure the recycled file is 1080p
				if [[ $tvSeason == *"1080p"* && $vCheck -eq 0 ]]; then
					let rCheck=0
				else
					if [[ $debug -ge "1" && $vCheck -eq "0" ]]; then
						echo "<font color='orange'><b>The file is not 1080p, skipping.</b></font>"
						echo ""
						let rCheck=1
					fi
				fi
#Check if the file is in use.
				if lsof "$tvSeason" > /dev/null; then
					echo "<font color='orange'><b>File is in use, skipping.</b></font>"
					echo ""
					inUse=1
				else
					inUse=0
				fi
#Parse the folder and Extension
				tvShowOriginal=$tvFolderRoot$tvShowName/$tvShowSeason/
				tvShowExtension=$(echo "$tvSeason" | cut -d'.' -f5)
#Check to see if the file matches a show
				if [ -d "${tvShowOriginal}" ]; then
					cd "${tvShowOriginal}"
#Search the folder for 4K shows
					if [[ $debug -ge "2" && $rCheck -eq "0" && $vCheck -eq "0" ]]; then
						echo "<font color='green'><b>Searching for: </b></font>${tvShowEpisode1}*2160p*.mkv"
					fi
					foundNew=$(find . -maxdepth 2 -name "${tvShowEpisode1}*2160p*.mkv")
					if [[ "$foundNew" != "" &&  $rCheck -eq "0" && $vCheck -eq "0" ]]; then
						if [ $debug -ge "1" ]; then
							echo "<font color='green'><b>Found matching 4K Show: </b></font>"$foundNew
						fi
					fi
					if [[ "$foundNew" = "" &&  $rCheck -eq "0" && $vCheck -eq "0" ]]; then
						echo "<font color='orange'><b>No matching 4K file found, skipping.</b></font>"
						echo ""
					fi	
#Parse movie name only if 4K filename found
					if [[ "$foundNew" == *"2160p"* &&  "$rCheck" = 0 && $vCheck -eq "0" ]]; then
						parseNameNew0=$(echo "$foundNew" | cut -d'[' -f1)
						parseNameNew1=$(echo "$parseNameNew0" | cut -d'/' -f2)
						parseNameNew2=${parseNameNew1}
						if [ $debug -ge "2" ]; then
							echo "<font color='red'><b>Name Comparison:</b></font> |" $parseNameOld0 "|" $parseNameNew2 "|"
						fi
						if [ "${parseNameOld0}" == "${parseNameNew2}" ]; then
							if [ $debug -ge "2" ] && [ $inUse -eq "0" ]; then
								echo "<font color='red'><b>Files Checked: </b></font>"$passNumber
							fi
							let passNumber++
							if [ $testing -eq "0" ]; then
								mv "${tvSeason}" "${tvShowOriginal}"
							fi
							/usr/local/emhttp/webGui/scripts/notify -e "Radarr Copy" -s "Copy Notifcation" -d "$parseNameNew2 $parseExt has been copied back." -i "normal"
							echo "<font color='green'><b>"$tvShowName" "$tvShowEpisode1" "$tvShowExtension" moved.</b></font>"
							echo ""
						fi
					fi
				fi
			fi
		done
	fi
done

if [[ passNumber -eq "1" ]]
then
echo "No files to process"
echo ""
echo ""
fi

#####################################
#
#          4K TV Show Sorter
#
#####################################

passNumber=1 #Counts how many files have been checked
inUse=0 #Saves if the file is in use and cancels
rCheck=0 #Set to 0 if it's ok to continue, 1 if it should end. (stands for Resolution Check)
vCheck=0 #Set to 0 if it's ok to continue, 1 if it skip the current file. (stands for Video Check)

echo "<hr>"
echo "<font color='blue'><b>Copying 4K TV Show's back.</b></font>"
echo ""
echo "<hr>"

for file in $binTV*
do
#Start checking TV shows.
	if [ "$(ls -A "$file")" ]; then
		directory=$file/
		for tvSeason in "${directory}"*/*
		do
			if [ -f "${tvSeason}" ]; then
				if [ $debug -ge "2" ]; then
					echo "<font color='green'><b>Full name: </b></font>"$tvSeason
				fi
#Parse the show name, episode and season
				parseNameOld0=$(echo "$tvSeason" | cut -d'/' -f9)
				parseNameOld0=$(echo "$parseNameOld0" | cut -d'[' -f1)
				tvShowName=$(echo "$tvSeason" | cut -d'/' -f7)
				tvShowSeason=$(echo "$tvSeason" | cut -d'/' -f8)
				tvShowEpisode0=$(echo "$tvSeason" | cut -d'/' -f9)
				tvShowEpisode1=$(echo "$tvShowEpisode0" | cut -d'-' -f1)
				if [ $debug -ge "1" ]; then
					echo "<font color='green'><b>Show name: </b></font>"$tvShowName
					echo "<font color='green'><b>Show episode: </b></font>"$tvShowEpisode1
				fi
#Check if the file is a video
				if [[ $tvSeason == *"mkv" ]]; then
					let vCheck=0 #Resets the Video Check for a new file
					let rCheck=0 #Resets the Continue Check for a new file
				else 
					echo "<font color='orange'><b>File isn't a video, skipping</b></font>"
					echo ""
					let vCheck=1					
				fi
#Ensure the recycled file is 4K
				if [[ $tvSeason == *"2160p"* && $vCheck -eq 0 ]]; then
					let rCheck=0
				else
					if [[ $debug -ge "1" && $vCheck -eq "0" ]]; then
						echo "<font color='orange'><b>The file is not 4K, skipping.</b></font>"
						echo ""
						let rCheck=1
					fi
				fi
#Check if the file is in use.
				if lsof "$tvSeason" > /dev/null; then
					echo "<font color='orange'><b>File is in use, skipping.</b></font>"
					echo ""
					inUse=1
				else
					inUse=0
				fi
#Parse the folder and Extension
				tvShowOriginal=$tvFolderRoot$tvShowName/$tvShowSeason/
				tvShowExtension=$(echo "$tvSeason" | cut -d'.' -f5)
#Check to see if the file matches a show
				if [ -d "${tvShowOriginal}" ]; then
					cd "${tvShowOriginal}"
#Search the new folder for Low-res shows
					if [[ $debug -ge "2" && $rCheck -eq "0" && $vCheck -eq "0" ]]; then
						echo "<font color='green'><b>Searching for: </b></font>${tvShowEpisode1}*1080p*.mkv"
					fi
					foundNew=$(find . -maxdepth 2 -name "${tvShowEpisode1}*1080p*.mkv")
					if [[ "$foundNew" != "" &&  $rCheck -eq "0" && $vCheck -eq "0" ]]; then
						if [ $debug -ge "1" ]; then
							echo "<font color='green'><b>Found matching Low-res Show: </b></font>"$foundNew
						fi
					fi
					if [[ "$foundNew" = "" &&  $rCheck -eq "0" && $vCheck -eq "0" ]]; then
						echo "<font color='orange'><b>No matching Low-res file found, skipping.</b></font>"
						echo ""
					fi	
#Parse movie name only if 1080p filename found
					if [[ "$foundNew" == *"1080p"* &&  "$rCheck" = 0 && $vCheck -eq "0" ]]; then
						parseNameNew0=$(echo "$foundNew" | cut -d'[' -f1)
						parseNameNew1=$(echo "$parseNameNew0" | cut -d'/' -f2)
						parseNameNew2=${parseNameNew1}
						if [ $debug -ge "2" ]; then
							echo "<font color='red'><b>Name Comparison:</b></font> |" $parseNameOld0 "|" $parseNameNew2 "|"
						fi
						if [ "${parseNameOld0}" == "${parseNameNew2}" ]; then
							if [ $debug -ge "2" ] && [ $inUse -eq "0" ]; then
								echo "<font color='red'><b>Files Checked: </b></font>"$passNumber
							fi
							let passNumber++
							if [ $testing -eq "0" ]; then
								mv "${tvSeason}" "${tvShowOriginal}"
							fi
							/usr/local/emhttp/webGui/scripts/notify -e "Radarr Copy" -s "Copy Notifcation" -d "$parseNameNew2 $parseExt has been copied back." -i "normal"
							echo "<font color='green'><b>"$tvShowName" "$tvShowEpisode1" "$tvShowExtension" moved.</b></font>"
							echo ""
						fi
					fi
				fi
			fi
		done
	fi
done

if [[ passNumber -eq "1" ]]
then
echo "No files to process"
echo ""
echo ""
fi

#####################################
#
#          Remove Empty Directories
#
#####################################

deletedDirCount=0

echo "<hr>"
echo "<font color='blue'><b>Removing empty directories.</b></font>"
echo ""
echo "<hr>"

#Clear empty movie bins
for emptyDir in $binMovie*
do
#Check that the scanned item is a directory
	if [ -d "${emptyDir}" ]
	then
#Check for empty directories only
		if [[ -z $(ls -A "$emptyDir") ]]
		then
#Log individual deleted files if advanced debugging is enabled.
			if [ $debug -ge "2" ]
				then
				echo "<font color='green'><b>Deleting: </b></font>"$emptyDir
			fi
#Actually do the removing and count how many directories have been deleted.
			if [ $testing -eq 0 ]
			then
				rmdir "${emptyDir}"
				let deletedDirCount++
			fi
		fi
	fi
done

#Clear empty tv show season bins (This has to be done before trying to remove the show folder)
for emptyDir in $binTV*
do
	for emptySeason in $binTV*/*
	do
#Check that the scanned item is a directory
		if [ -d "${emptySeason}" ]
		then
#Check for empty directories only
			if [[ -z $(ls -A "$emptySeason") ]]
			then
#Log individual deleted files if advanced debugging is enabled.
				if [ $debug -ge "2" ]
					then
					echo "<font color='green'><b>Deleting: </b></font>"$emptySeason
				fi
#Actually do the removing and add to how many directories have been deleted.
				if [ $testing -eq 0 ]
				then
					rmdir "${emptySeason}"
					let deletedDirCount++
				fi
			fi
		fi
	done
done

#Clear empty tv show bins (this has to be done after removing the seasons first [above])
for emptyDir in $binTV*
do
#Check that the scanned item is a directory
	if [ -d "${emptyDir}" ]
	then
#Check for empty directories only
		if [[ -z $(ls -A "$emptyDir") ]]
		then
#Log individual deleted files if advanced debugging is enabled.
			if [ $debug -ge "2" ]
				then
				echo "<font color='green'><b>Deleting: </b></font>"$emptyDir
			fi
#Actually do the removing and add to how many directories have been deleted.
			if [ $testing -eq 0 ]
			then
				rmdir "${emptyDir}"
				let deletedDirCount++
			fi
		fi
	fi
done

#Log the deleted files and print message if testing is enabled instead.
if [ $testing -eq 0 ]
then
	echo "<font color='green'><b>Empty directories deleted: </b></font>"$deletedDirCount
else
	echo "<font color='orange'><b>Testing is enabled, so nothing has been deleted.</b></font>"
fi

#Send a notification with total files copied.
let passNumber--

#Notification where nothing was deleted but files were copied.
if [[ $passNumber -gt 1 && $testing -eq 0 && $deletedDirCount -eq 0 ]]
then
	/usr/local/emhttp/webGui/scripts/notify -e "Radarr Copy" -s "Copy Notifcation" -d "$passNumber files have been copied." -i "warning"
fi

#Notification where directories were deleted and files were copied.
if [[ $passNumber -gt 1 && $testing -eq 0 && $deletedDirCount -gt 0 ]]
then
	/usr/local/emhttp/webGui/scripts/notify -e "Radarr Copy" -s "Copy Notifcation" -d "$passNumber files have been copied, and $deletedDirCount empty directories have been deleted." -i "warning"
fi
